# Generated by Django 4.2.20 on 2025-04-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_guides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyguide',
            name='file_text_data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
