# Generated by Django 4.2.20 on 2025-04-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_guides', '0002_studyguide_file_text_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyguide',
            name='file_text_data',
            field=models.TextField(blank=True),
        ),
    ]
