# Generated by Django 4.2.20 on 2025-04-30 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_guides', '0003_alter_studyguide_file_text_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textstudyguide',
            name='study_guide',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outline', to='study_guides.studyguide'),
        ),
        migrations.CreateModel(
            name='FlashCardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('study_guide', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='study_guides.studyguide')),
            ],
        ),
    ]
