# Generated by Django 4.2.20 on 2025-05-21 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_guides', '0004_alter_textstudyguide_study_guide_flashcardset'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('study_guide', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multi_choice_test', to='study_guides.studyguide')),
            ],
        ),
    ]
